import { applyStudioMigrations } from './migrations.mjs';
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile, mkdir } from 'node:fs/promises';
import { getPlatformProxy } from 'wrangler';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import worker from '../../cloudflare/worker.mjs';
import { launchChromium } from '../ui/helpers/browser.mjs';
import { serveDirectory } from '../ui/helpers/static-server.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
test('Dashboard real: criação, edição, modais, lixeira, foco, temas e celular', { timeout: 120000 }, async t => {
  const proxy = await getPlatformProxy({ persist: false });
  t.after(() => proxy.dispose());
  const db = proxy.env.DB;
  await applyStudioMigrations(db);
  const server = await serveDirectory(root); t.after(() => server.close());
  const browser = await launchChromium(); t.after(() => browser.close());
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce', colorScheme: 'light' });
  const env = { ...proxy.env, LOCAL_DEV: 'true', SITE_ORIGIN: server.origin };
  const errors = [];
  await context.addInitScript(() => sessionStorage.setItem('intro-shown-v1', '1'));
  // HTTP UI uses the production Worker and an isolated real local D1 binding.
  // Third-party mail is intercepted: no messages or tests reach production.
  await context.route('**/*', async route => {
    const request = route.request(), url = new URL(request.url());
    if (url.origin !== server.origin) {
      if (url.hostname === 'api.web3forms.com') return route.fulfill({ status: 200, contentType: 'application/json', body: '{"success":true}' });
      if (request.resourceType() === 'stylesheet') return route.fulfill({ status: 200, contentType: 'text/css', body: '' });
      return route.fulfill({ status: 204, body: '' });
    }
    if (url.pathname.startsWith('/api/') || ['/content.js', '/portfolio-content.js', '/prompts.mjs'].includes(url.pathname)) {
      const response = await worker.fetch(new Request(request.url(), { method: request.method(), headers: await request.allHeaders(), ...(request.postData() ? { body: request.postData() } : {}) }), env);
      return route.fulfill({ status: response.status, headers: Object.fromEntries(response.headers), body: await response.text() });
    }
    return route.continue();
  });
  const page = await context.newPage(); page.on('pageerror', e => errors.push(e.message));
  await page.goto(server.origin + '/admin.html');
  await page.getByLabel('Senha', { exact: true }).fill('wrong');
  await page.getByRole('button', { name: 'Entrar no studio' }).click();
  await page.getByText('Usuário ou senha incorretos.').waitFor();
  await page.getByLabel('Senha', { exact: true }).fill('admin123');
  await page.getByRole('button', { name: 'Entrar no studio' }).click();
  await page.getByRole('heading', { name: 'Todos os conteúdos' }).waitFor();
  assert.equal(await page.locator('#eyebrow').count(), 0);
  await mkdir(path.join(root, 'artifacts/admin'), { recursive: true });
  await page.addScriptTag({ path: path.join(root, 'node_modules/axe-core/axe.min.js') });
  async function axe(label) {
    const violations = await page.evaluate(async () => (await window.axe.run({ runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } })).violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) })));
    assert.deepEqual(violations, [], label);
  }
  await axe('dashboard light');
  assert.equal(await page.locator('.admin-nav-count').count(), 0);
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Pessoas', exact: true }).isVisible(), false);
  await page.reload();
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Pessoas', exact: true }).isVisible(), false);
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).press('Enter');
  await page.addScriptTag({ path: path.join(root, 'node_modules/axe-core/axe.min.js') });
  await page.getByRole('button', { name: 'Alternar tema' }).hover();
  await page.locator('.admin-tooltip[data-open="true"]').waitFor();
  assert.equal(await page.getByRole('tooltip').textContent(), 'Alternar tema');
  await page.keyboard.press('Escape');
  await page.getByRole('tooltip').waitFor({ state: 'hidden' });
  await page.mouse.move(500, 200);
  await page.screenshot({ path: path.join(root, 'artifacts/admin/dashboard-light.png') });
  // Typography floor (05/09/2026): nothing below Medium; what carried emphasis
  // steps up to Semibold; the sub-label and overview numbers left 400 behind.
  assert.deepEqual(await page.evaluate(() => ['body', 'h1', '.admin-brand-sub', '.admin-overview strong', '.admin-nav-item'].map(s => getComputedStyle(document.querySelector(s)).fontWeight)), ['500', '600', '500', '500', '500']);
  // Studio typeface: slider popover above the user block, keyboard-first.
  const typefaceTrigger = page.locator('.admin-typeface-trigger');
  await typefaceTrigger.click();
  const slider = page.getByRole('slider', { name: 'Família tipográfica do Studio' });
  await page.waitForFunction(() => document.activeElement?.classList.contains('admin-typeface-range'));
  assert.equal(await typefaceTrigger.getAttribute('aria-expanded'), 'true');
  await axe('typeface popover');
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.evaluate(() => document.documentElement.dataset.typeface), 'mono');
  assert.match(await page.evaluate(() => getComputedStyle(document.body).fontFamily), /^"Geist Mono"/);
  assert.equal(await slider.getAttribute('aria-valuetext'), 'Geist Mono');
  assert.equal(await typefaceTrigger.getAttribute('aria-label'), 'Fonte do Studio: Geist Mono');
  await page.keyboard.press('End');
  // Pixel: the one accepted exception to the floor — native 400, Square grid.
  assert.deepEqual(await page.evaluate(() => [document.documentElement.dataset.typeface, getComputedStyle(document.body).fontWeight, getComputedStyle(document.querySelector('h1')).fontWeight, getComputedStyle(document.body).fontVariationSettings, getComputedStyle(document.body).fontFamily.startsWith('"Geist Pixel"')]), ['pixel', '400', '400', '"ELSH" 1', true]);
  await page.keyboard.press('Escape');
  await page.locator('#admin-typeface-popover:popover-open').waitFor({ state: 'hidden' });
  await page.waitForFunction(() => document.querySelector('.admin-typeface-trigger').getAttribute('aria-expanded') === 'false');
  assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('aria-label')), 'Fonte do Studio: Geist Pixel');
  await page.reload();
  // Restored by admin/theme.js in <head>, before the app boots — no Sans flash.
  assert.equal(await page.evaluate(() => document.documentElement.dataset.typeface), 'pixel');
  await page.getByRole('heading', { name: 'Todos os conteúdos' }).waitFor();
  assert.equal(await typefaceTrigger.textContent(), 'Geist Pixel');
  await typefaceTrigger.click();
  await page.waitForFunction(() => document.activeElement?.classList.contains('admin-typeface-range'));
  await page.keyboard.press('Home');
  assert.equal(await page.evaluate(() => document.documentElement.dataset.typeface), 'sans');
  await page.keyboard.press('Escape');
  await page.locator('#admin-typeface-popover:popover-open').waitFor({ state: 'hidden' });
  await page.addScriptTag({ path: path.join(root, 'node_modules/axe-core/axe.min.js') });
  const expandedWidth = await page.locator('.admin-workspace').evaluate(el => el.getBoundingClientRect().width);
  await page.getByRole('button', { name: 'Recolher sidebar' }).click();
  assert.ok(await page.locator('.admin-workspace').evaluate(el => el.getBoundingClientRect().width) > expandedWidth);
  // Icon-only in the rail: the shared tooltip names the current family.
  await page.mouse.move(0, 0);
  await typefaceTrigger.hover();
  await page.locator('.admin-tooltip[data-open="true"]').waitFor();
  assert.equal(await page.getByRole('tooltip').textContent(), 'Fonte do Studio: Geist Sans');
  await page.keyboard.press('Escape');
  await page.getByRole('tooltip').waitFor({ state: 'hidden' });
  await page.mouse.move(500, 200);
  await axe('sidebar collapsed');
  await page.reload();
  await page.getByRole('button', { name: 'Expandir sidebar' }).waitFor();
  await page.getByRole('button', { name: 'Projetos', exact: true }).click();
  await page.getByRole('heading', { name: 'Projetos', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Expandir sidebar' }).press('Enter');
  await page.getByRole('button', { name: 'Todos os conteúdos', exact: true }).click();
  await page.addScriptTag({ path: path.join(root, 'node_modules/axe-core/axe.min.js') });
  await page.getByRole('button', { name: 'Novo conteúdo', exact: true }).click();
  await page.getByLabel('Identificador', { exact: true }).fill('ui-test-project');
  await page.getByLabel('Título', { exact: true }).fill('Projeto de teste local');
  await page.getByLabel('Subtítulo', { exact: true }).fill('Design engineering');
  await page.getByLabel('Descrição do modal', { exact: true }).fill('Conteúdo salvo no D1.');
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByLabel('Buscar conteúdo').fill('Projeto de teste local');
  const row = page.getByRole('button', { name: /Projeto de teste local.*Rascunho/ }); await row.waitFor();
  const site = await context.newPage(); site.on('pageerror', e => errors.push(e.message));
  await site.goto(server.origin + '/');
  assert.equal(await site.locator('[data-open="projects:ui-test-project"]').count(), 0);
  await row.click();
  await page.getByRole('combobox', { name: 'Visibilidade', exact: true }).selectOption('false');
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await site.reload();
  await site.locator('#projectsSeeMore').click();
  await site.locator('[data-open="projects:ui-test-project"]').click();
  await site.locator('.cmd-modal[aria-hidden="false"]').waitFor();
  assert.match(await site.locator('#cmdModal').textContent(), /Conteúdo salvo no D1/);
  await page.getByRole('button', { name: /Projeto de teste local.*Visível/ }).click();
  await axe('editor light');
  await page.screenshot({ path: path.join(root, 'artifacts/admin/editor-light.png') });
  await page.getByLabel('Título', { exact: true }).fill('Mudança ainda não salva');
  await page.keyboard.press('Escape');
  await page.getByRole('dialog', { name: 'Descartar alterações?' }).waitFor();
  await page.getByRole('button', { name: 'Continuar editando' }).click();
  assert.equal(await page.getByLabel('Título', { exact: true }).inputValue(), 'Mudança ainda não salva');
  await page.keyboard.press('Escape'); await page.getByRole('button', { name: 'Descartar', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.match(await page.evaluate(() => document.activeElement.textContent), /Projeto de teste local/);
  await page.getByRole('button', { name: /Projeto de teste local.*Visível/ }).click();
  await page.getByRole('button', { name: 'Mover para a lixeira' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await site.goto(server.origin + '/'); assert.equal(await site.locator('[data-open="projects:ui-test-project"]').count(), 0);
  await page.getByRole('button', { name: /^Lixeira/ }).click();
  await page.getByRole('button', { name: 'Restaurar', exact: true }).click();
  await page.getByRole('button', { name: /^Pessoas/ }).click();
  await page.getByRole('button', { name: 'Novo conteúdo', exact: true }).click();
  await page.getByLabel('Identificador').fill('ui-test-person');
  await page.getByLabel('Título', { exact: true }).fill('Pessoa de teste');
  await page.getByLabel('Subtítulo').fill('Design');
  await page.getByLabel('Descrição do modal').fill('Uma pessoa adicionada pelo dashboard.');
  await page.getByRole('combobox', { name: 'Visibilidade', exact: true }).selectOption('false');
  await page.getByRole('button', { name: 'Salvar alterações' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await site.goto(server.origin + '/wiki');
  await site.locator('[data-person="ui-test-person"]').click();
  assert.match(await site.locator('#panel').textContent(), /Uma pessoa adicionada pelo dashboard/);
  await page.getByLabel('Buscar conteúdo').fill('Pessoa de teste');
  await page.getByRole('button', { name: /Pessoa de teste.*Visível/ }).click();
  await page.getByRole('button', { name: 'Mover para a lixeira' }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await site.reload(); assert.equal(await site.locator('[data-person="ui-test-person"]').count(), 0);
  await page.getByRole('button', { name: /^Todos os conteúdos/ }).click();
  await page.getByRole('button', { name: 'Alternar tema' }).click();
  await axe('dashboard dark');
  await page.screenshot({ path: path.join(root, 'artifacts/admin/dashboard-dark.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Recolher sidebar' }).click();
  assert.equal(await page.getByRole('navigation', { name: 'Coleções de conteúdo' }).isVisible(), false);
  await page.getByRole('button', { name: 'Expandir sidebar' }).click();
  assert.equal(await page.getByRole('button', { name: 'Sair do studio' }).isVisible(), true);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await axe('mobile dark');
  // Phones hide the sidebar foot, so the typeface control moves to the topbar
  // and its popover opens below it, inside the viewport.
  const mobileTypeface = page.locator('.admin-mobile-typeface');
  assert.equal(await mobileTypeface.isVisible(), true);
  assert.equal(await typefaceTrigger.isVisible(), false);
  await mobileTypeface.click();
  await page.waitForFunction(() => document.activeElement?.classList.contains('admin-typeface-range'));
  const popoverBox = await page.locator('#admin-typeface-popover').boundingBox(), triggerBox = await mobileTypeface.boundingBox();
  assert.ok(popoverBox.x >= 0 && popoverBox.x + popoverBox.width <= 390 && popoverBox.y >= triggerBox.y + triggerBox.height, 'popover sits below the topbar trigger, inside the viewport');
  await axe('mobile typeface popover');
  await page.keyboard.press('Escape');
  await page.locator('#admin-typeface-popover:popover-open').waitFor({ state: 'hidden' });
  assert.equal(await page.evaluate(() => document.activeElement?.classList.contains('admin-mobile-typeface')), true);
  await page.screenshot({ path: path.join(root, 'artifacts/admin/dashboard-mobile.png') });
  await page.getByRole('button', { name: 'Novo conteúdo', exact: true }).click();
  assert.equal(await page.evaluate(() => document.querySelector('dialog').scrollWidth <= innerWidth), true);
  await axe('mobile editor dark');
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 320, height: 740 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  // Cursor stays on top of native dialogs and does not idle away on inputs.
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.reload(); await page.getByRole('heading', { name: 'Todos os conteúdos' }).waitFor();
  await page.getByRole('button', { name: 'Novo conteúdo', exact: true }).click();
  await page.getByLabel('Título', { exact: true }).hover();
  await page.waitForFunction(() => document.querySelector('.ipad-cursor')?.dataset.mode === 'text');
  await page.waitForTimeout(2400);
  assert.equal(await page.locator('.ipad-cursor').evaluate(el => el.matches(':popover-open')), true);
  assert.ok(Number(await page.locator('.ipad-cursor').evaluate(el => getComputedStyle(el).opacity)) > .9);
  assert.deepEqual(errors, []);
});
